### ISSUE TITLE
[ and ] displayed as Unicode chars

### ISSUE THREAD

**Issue by EXSolo** [UltraSoftcore/Match-Calendar#91]
http://puu.sh/gdzw7/8bff38605e.jpg
http://puu.sh/gdzvc/2d9149bc32.png

**Comment by Eluinhost** [comment]
I'm pretty sure this is the same thing as & was a while back, I'll take a closer look and fix all escaped characters (pretty sure it was because they were returned in the api like that and then angular escapes the escape?)

**Comment by Eluinhost** [comment]
On my PC [ and ] were working correctly and so was ' but < and > were showing as &lt; and &gt;

Post body doesn't have any of the issues.
